name: compilation check

on:
  push:
    branches: [ "validated" ]
  pull_request:
    branches: [ "validated" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: compilation check
      run: cd ft_irc; make; ./ircserv 6667 PASS && sleep 3
